// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdAlfdB6eA2DVqgR7Np7z84Av5c_g69vI',
    appId: '1:104922924776:web:dc6094476d45b87365ab5d',
    messagingSenderId: '104922924776',
    projectId: 'gurmeet-building-material',
    authDomain: 'gurmeet-building-material.firebaseapp.com',
    storageBucket: 'gurmeet-building-material.firebasestorage.app',
    measurementId: 'G-B9N8ZDSVDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsD7X5-qDTOfgGX3SCXVraGhj866S1kg',
    appId: '1:104922924776:android:6e597227b92468aa65ab5d',
    messagingSenderId: '104922924776',
    projectId: 'gurmeet-building-material',
    storageBucket: 'gurmeet-building-material.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATK5ixD-3BSOblwlaeI2M7mVOftEfiuK4',
    appId: '1:104922924776:ios:87ac2db5925f959b65ab5d',
    messagingSenderId: '104922924776',
    projectId: 'gurmeet-building-material',
    storageBucket: 'gurmeet-building-material.firebasestorage.app',
    iosBundleId: 'com.gurmeet.buildingmaterialbilling.buildingMaterialBilling',
  );
}
